name: pezgurly
favicon: null
layout_spectrum: 0.50829
typography_spectrum: 0.3007
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#100503'
    - '#f2f5fa'
    - '#d48c74'
    - '#293728'
    - '#8ba13d'
  brandStrength: 0.875
  lightness: 0.75
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
